version: '3.1'

services:
  db:
    image: postgres
    restart: always
    # Make sure to include the nessary sql files under ./sql
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
    environment:
      - "POSTGRES_USER=docker"
      - "POSTGRES_PASSWORD=docker"
    ports:
      - "5432:5432"