name: Database

on:
  workflow_dispatch:

jobs:
  Database:
    name: Setup Database
    runs-on: [self-hosted, Linux, ARM64]

    # https://docs.github.com/en/actions/tutorials/use-containerized-services/create-postgresql-service-containers#configuring-the-steps-for-jobs-directly-on-the-runner-machine
    steps:
        # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v6

      ## This is incomplete

      - name: Setup database, schema, tables
        run: docker exec -i postgres-container psql -U postgres -d postgres < ./sql/setupDBT.sql
      
      - name: Setup dbt models
        run: |
          cd dbtproject
          dbt run      