name: Pipeline

on:
  workflow_dispatch:

jobs:
  Pipeline:
    name: Setup Pipeline
    if: ${{ github.event.inputs.target_pipeline == 'Pipeline 1' || github.event.inputs.target_pipeline == 'Both' }}
    runs-on: [self-hosted, macOS, ARM64]
    defaults:
      run:
        working-directory: /Users/jonathankee/examTopicScraper
    steps:
      - name: Print working directory
        run: |
          pwd

      - name: Clear existing documents
        run: rm -rf /Users/jonathankee/examTopicScraper/static_page/src/main/resources/tmp/*

      - name: Run jar for Download document
        run: | 
          cd static_page
          java -jar /Users/jonathankee/examTopicScraper/static_page/Download/build/libs/Download-all.jar "1z0-071"
          
      - name: Run jar for Insert Data into Database from documents
        run: |
          cd static_page    
          java -jar /Users/jonathankee/examTopicScraper/static_page/Document/build/libs/Document-all.jar

      # Make sure to have the browser to automate open
      - name: Rescape missing data
        run: tsc && node ./build/commands/rescrapeDataMissingAnswers.js '1z0-071'

      - name: Clear existing images
        run: rm -rf /Users/jonathankee/examTopicScraper/static_page/src/main/resources/images/*
        
      - name: Run jar for Download images
        run: |
          cd static_page
          java -jar /Users/jonathankee/examTopicScraper/static_page/Image/build/libs/Image-all.jar

      - name: Copy over the files to images
        run: | 
          rm -rf images/*
          cp /Users/jonathankee/examTopicScraper/static_page/src/main/resources/images/* /Users/jonathankee/examTopicScraper/images/

      - name: Run ALTER SEQUENCE scrape.seq_markdown RESTART WITH 1
        run: echo "ALTER SEQUENCE scrape.\"seq_markdown\" RESTART WITH 1;" | docker exec -i postgres-container psql -U postgres -d exam_topic
      
      - name: Run markdown command
        run: tsc && node ./build/commands/markdown.js '1z0-071' 272